### ISSUE TITLE
Write tool description (HTML meta tag)

### ISSUE THREAD

**Issue by moroshko** [moroshko/accessible-colors#23]
This will be displayed by Google in the search results page.
Note: This won't be used by the search engine. It should be designed to users to read, and should improve the click through rate.

**Comment by vedranio** [comment]
1.
Accessible Color lets you easily test your text/background contrast ratio against WCAG AA and AAA standards. It automatically suggests the closest accessible color combination, if your design does not meet the standards.

2.
Accessible Color automatically suggests the closest accessible color combination, if your design does not meet WCAG AA and AAA standards.

3.
Accessible Color tests your text/background contrast ratio against WCAG 2.0 standard, and automatically suggests the closest accessible color combination.

**Comment by vedranio** [comment]
Decided on the following

"Test your text/background contrast ratio based on Web Content Accessibility Guidelines (WCAG), and automatically find the closest accessible color combination."
