### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by moroshko** [moroshko/accessible-colors#6]

**Comment by vedranio** [comment]
Medium: 768px > width > 509px
- H1 is 49px
- H2 is 18px
- change default input font size to 14px
- change size of input controls and all other headings to 18px

Small: 509px > width > 319px
- H1 is 28px
- H2 is 14px
- change default input font value to 14px
- change size of input controls and all other headings to 18px

**Comment by vedranio** [comment]
Limit the size of text we accept to 18px on medium and small devices
