### ISSUE TITLE
Minimum font size

### ISSUE THREAD

**Issue by kaylajheffernan** [moroshko/accessible-colors#63]
I'm trying to assess if someone else's work is accessible, and they are using 8px. Your tool currently has a minimum font size of 10px. 

It would be great if we could go smaller

**Comment by vedranio** [comment]
Hey @kaylajheffernan we could easily do this, however, technically there is no difference between contrast accessibility between 8pt and 10pt font. The formula used to evaluate the contrast is the same, it only changes once you go over 18pt.

Of course, there is a material difference in how you or anyone perceives the text. 

We'll talk about changing this

**Comment by vedranio** [comment]
Have allowed minimum size of 8px (which is equal to ~11pt)
