### ISSUE TITLE
Correct support of "large font" AA ratio of 3:1

### ISSUE THREAD

**Issue by nathanbiehl** [moroshko/accessible-colors#70]
AA threshold for "large fonts" is _3:1_ and not 4.5:1. WCAG 2.0 considers "Large fonts" to be 14pt bold and larger _or_ 18pt regular and larger.  Your default example on http://accessible-colors.com should pass all AA examples. Neither it nor 14pt bold pass currently:  

<img width="700" alt="screen shot 2017-10-11 at 1 41 56 pm" src="https://user-images.githubusercontent.com/4493225/31459886-335567d4-ae8a-11e7-8314-efa33c4de5c1.png">
<img width="700" alt="screen shot 2017-10-11 at 1 42 07 pm" src="https://user-images.githubusercontent.com/4493225/31459885-3320fda0-ae8a-11e7-86b9-54d9307a6fc8.png">

**Comment by moroshko** [comment]
Note that `pt` is mentioned in the guidelines, not `px`.
If you switch to `pt`, it will pass AA.
[1pt = 1.333px](http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html#visual-audio-contrast-contrast-73-head)

**Comment by nathanbiehl** [comment]
Uff da, I was a space cadet on those details. Thanks for the clarification!
